### ISSUE TITLE
请审核，谢谢 :p

### ISSUE THREAD

**Issue by taseikyo** [cnblogs/cnblogs-hardening#1052]
https://www.cnblogs.com/cmt/p/14580194.html

**Comment by cnblogs-team** [comment]
您好，博文地址不对，麻烦您提供一下正确的博文地址或者标题

**Comment by taseikyo** [comment]
跳转之后的地址应该就是这个没错啊 😂

标题：bib+windows+word=bibtex4word插件使用方法- PiaYie - 博客园

![20210414162725](https://user-images.githubusercontent.com/23132915/114678963-54224f80-9d3e-11eb-99ec-283016aad6bf.png)

https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2FPiaYie%2Fp%2F14457485.html

**Comment by cnblogs-team** [comment]
您好，已审核通过，抱歉，给您带来麻烦了
https://www.cnblogs.com/PiaYie/p/14457485.html

**Comment by taseikyo** [comment]
谢谢！
