### ISSUE TITLE
check

### ISSUE THREAD

**Issue by 0zheermao0** [cnblogs/cnblogs-hardening#130]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fweblogical%2Farchive%2F2011%2F03%2F07%2F1974585.html

**Comment by cnblogs-team** [comment]
您好，已审核通过，非常非常抱歉，由于github邮件通知问题，现在才回复您，请谅解
https://www.cnblogs.com/weblogical/archive/2011/03/07/1974585.html
