### ISSUE TITLE
关于sqlserver的帖子

### ISSUE THREAD

**Issue by LibreBai** [cnblogs/cnblogs-hardening#1365]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fcindy1989%2Farchive%2F2012%2F06%2F07%2F2540486.html&blogId=89665&postId=2540486

**Comment by cnblogs-team** [comment]
您好，已通过审核 https://www.cnblogs.com/cindy1989/archive/2012/06/07/2540486.html ，给您带来麻烦实在是抱歉。
