### ISSUE TITLE
麻烦审核团队提前审核《ES6 开发规范-最佳实践》

### ISSUE THREAD

**Issue by ivanchen008** [cnblogs/cnblogs-hardening#138]
博客园团队：
    你好，目前这篇博文只在cnblogs有发布，没有在其他平台找到类似的文章，希望团队审核能够提前审核。
    博客文章：《ES6 开发规范-最佳实践》
    作者：草漾 2018-10-21
    链接如下：https://www.cnblogs.com/wuchenfei/p/9824640.html  ，
    辛苦审核团队！！！

**Comment by ivanchen008** [comment]
![image](https://user-images.githubusercontent.com/17905378/112721269-f0c2b000-8f3d-11eb-9978-999e69234ee4.png)

**Comment by cnblogs-team** [comment]
您好，已审核通过，非常非常抱歉，由于github邮件通知问题，现在才处理，请谅解
https://www.cnblogs.com/wuchenfei/p/9824640.html
