### ISSUE TITLE
麻烦审核

### ISSUE THREAD

**Issue by xiexu666** [cnblogs/cnblogs-hardening#1447]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Frichardcpp%2Farchive%2F2013%2F03%2F17%2F2964892.html&blogId=130198&postId=2964892

**Comment by cnblogs-team** [comment]
您好，已审核通过，抱歉，给您带来麻烦了
https://www.cnblogs.com/richardcpp/archive/2013/03/17/2964892.html
