### ISSUE TITLE
审核

### ISSUE THREAD

**Issue by limanman1005** [cnblogs/cnblogs-hardening#1457]
您好，这篇文章作者讲解的Fabric非常好。建议将这个作者关于Fabric的文章全部审核一下。这是其中的一篇，麻烦了。
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Falways-kaixuan%2Fp%2F12398251.html&blogId=406023&postId=12398251

**Comment by cnblogs-team** [comment]
您好，已通过审核 https://www.cnblogs.com/always-kaixuan/p/12398251.html ，给您带来麻烦实在是抱歉。
