### ISSUE TITLE
Check it, plz! Thanks.

### ISSUE THREAD

**Issue by Marx-htf** [cnblogs/cnblogs-hardening#1496]
https://www.cnblogs.com/cmt/p/14580194.html

**Comment by Marx-htf** [comment]
how to prove the article is writen by myself? Give me some advice!

**Comment by cnblogs-team** [comment]
Hello, please provide the actual address(not the redirected one) of your post, then we can look into it.

**Comment by Marx-htf** [comment]
I also leave a message on your website. It seems you've checked it, right? If not, please check it again.
www.cnblogs.com/w-netboy/p/12185833.html
www.cnblogs.com/w-netboy/p/12074683.html

**Comment by cnblogs-team** [comment]
These links are already been reviewed and viewable to everyone.
