### ISSUE TITLE
麻烦尽快恢复这篇博客

### ISSUE THREAD

**Issue by lookforwardxu** [cnblogs/cnblogs-hardening#16]
https://www.cnblogs.com/cmt/p/14580194.html

**Comment by cnblogs-team** [comment]
您好，麻烦您现在重新访问并提交一下网址，现在会在 url 查询参数中记录原始网址

**Comment by lookforwardxu** [comment]
> 您好，麻烦您现在重新访问并提交一下网址，现在会在 url 查询参数中记录原始网址

https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fchentianxiang180%2Fp%2F12303422.html

**Comment by cnblogs-dudu** [comment]
您好，抱歉，给您带来麻烦了，已恢复访问 https://www.cnblogs.com/chentianxiang180/p/12303422.html
