### ISSUE TITLE
请审核，谢谢

### ISSUE THREAD

**Issue by zhiyang-jzy** [cnblogs/cnblogs-hardening#1609]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fstarfallen%2Farchive%2F2013%2F05%2F22%2F3091823.html&blogId=132671&postId=3091823

**Comment by cnblogs-team** [comment]
您好，已审核通过 https://www.cnblogs.com/starfallen/archive/2013/05/22/3091823.html
