### ISSUE TITLE
2021-07-07 谁能告诉我博客园怎么了？域名 https://www.cnblogs.com/ 访问不了了！

### ISSUE THREAD

**Issue by BensonLaur** [cnblogs/cnblogs-hardening#1723]
有点伤心，用了好多年了

**Comment by cnblogs-team** [comment]
您好，现在大部分博文已经恢复正常访问了

**Comment by BensonLaur** [comment]
> 
> 
> 您好，现在大部分博文已经恢复正常访问了

太好了，官方有人在！
你好，感谢你们的工作，我的博文在之前邮件申请后恢复了，现在的情况不太一样。似乎是整个网站上不了了，比如 

[https://www.cnblogs.com](https://www.cnblogs.com)
[https://www.cnblogs.com/BensonLaur/p/9695769.html](https://www.cnblogs.com/BensonLaur/p/9695769.html)

难道是只有我这边上不了？可以麻烦确认下吗？谢谢！

**Comment by cnblogs-team** [comment]
您好，这边可以正常访问，麻烦您检查下您的网络情况

**Comment by BensonLaur** [comment]
> 
> 
> 您好，这边可以正常访问，麻烦您检查下您的网络情况

这样子？不应该呀，我所有其他网站都正常上才对，百度、知乎、bilibili、csdn、msdn、简书等，搭了梯子之后，google，gmail, facebook, YouTube, stackoverflow，github 都可以，就是这个 https://www.cnblogs.com 不行，以及其所有的文章。

有没有可能有 IP 限制等策略什么的，不过我也有一小段时间（两三天）没上了，不应该呀

**Comment by cnblogs-team** [comment]
您好，麻烦您不使用vpn后再试试呢？

**Comment by BensonLaur** [comment]
> 
> 
> 您好，麻烦您不使用vpn后再试试呢？

我一开始也有点怀疑这一点，还考虑是不是用了多个的问题，刚刚详细确认了一下，确认都不使用VPN后，也是不行。
另外，我是使用手机发的热点（宽带没接了），网络服务供应商是中国移动；电脑不行后，我试了用手机本身浏览器上，然后用平板电脑连接热点上，均无法访问。

可能得明天去公司再访问一下博客园对比看看了，感谢您的答复，我明天再看看是什么情况

**Comment by cnblogs-team** [comment]
@BensonLaur 麻烦您 `ping www.cnblogs.com` 提供一下返回的 IP 地址

**Comment by BensonLaur** [comment]
> 
> 
> @BensonLaur 麻烦您 `ping www.cnblogs.com` 提供一下返回的 IP 地址

很可惜的是，我没法复现了。
不过我可以说一下这边最新的操作回顾
1. 到公司后，我首先在电脑上使用`公司WIFI` 访问`www.cnblogs.com`, 确认可以访问
2. 然后在手机浏览器上，用`手机自己的网络`，访问 `www.cnblogs.com`，还是和昨天一样上不了
3. 接着我用手机连接`公司WIFI`，这回上得了了
4. 于是我为了对比，我让一位使用 IPhone 以及联通卡的一位同事，用`手机自己的网络` 访问 `www.cnblogs.com`，可以访问
5. 正当我疑惑为什么他`手机自己的网络`可以访问而我`手机自己的网络`不可以时，我再断开`公司WIFI`使用我`手机自己的网络`访问`www.cnblogs.com`，这回出乎当时意料地，这回上得了了

然后看到你的回复让我 ping 一下看看返回的 IP，结合我这边之前遇到的一个相关的经历（之前公司有2个网络，IP不一样，连接一个访问不了百度，连接另一个访问不了，后面 ping 了下百度地址，发现返回的 IP 不一样）。
我觉得这个这次遇到的访问不了`www.cnblogs.com` 也是和那一次访问不了百度类似的原因，因为这个现象很相似，都是类似这样的现象：
1. 在`设备1`上，`网络A`暂时访问不了`目标域名T`解析得到的服务器（`IP_1`）
2. 在`设备2`上，`网络B`访问可以正常访问`目标域名T`解析得到的服务器（`IP_2`）
3. 发现了`2`后，在`设备1`上，连接`网络B`，发现可以正常访问`目标域名T`解析得到的服务器（`IP_2`）
4. 重新将`设备1`连接到 `网络A`，发现最终可以访问`目标域名T`解析得到的服务器（`IP_2`）

所以，结论应该是 `www.cnblogs.com` 和 百度一样，在某个时刻某些服务器IP失效了（IP变化或某台服务器节点在更新或出问题了），而用户端的网络由于某些原因没能自动刷新得到新的服务器 IP 导致的结果

**Comment by cnblogs-team** [comment]
您好，我们用的是阿里云负载均衡，最近IP地址没有发生变化，可能是DNS解析的问题

**Comment by BensonLaur** [comment]
> 
> 
> 您好，我们用的是阿里云负载均衡，最近IP地址没有发生变化，可能是DNS解析的问题

好的，感谢反馈！
