### ISSUE TITLE
麻烦优先审核一下，谢谢！

### ISSUE THREAD

**Issue by i-Clay** [cnblogs/cnblogs-hardening#195]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fpolebug%2Farchive%2F2014%2F01%2F02%2F3502565.html

**Comment by cnblogs-team** [comment]
您好，已审核通过，非常非常抱歉，由于github邮件通知问题，现在才处理，请谅解
https://www.cnblogs.com/polebug/archive/2014/01/02/3502565.html
