### ISSUE TITLE
请审核下

### ISSUE THREAD

**Issue by mafiaun** [cnblogs/cnblogs-hardening#206]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fpunkrocker%2Farchive%2F2012%2F09%2F01%2F2666307.html
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fwangx036%2Fp%2F14084075.html

**Comment by cnblogs-team** [comment]
您好，已审核通过，非常非常抱歉，由于github邮件通知问题，现在才处理，请谅解
https://www.cnblogs.com/punkrocker/archive/2012/09/01/2666307.html
https://www.cnblogs.com/wangx036/p/14084075.html
