### ISSUE TITLE
请问博客的备份功能怎么不能用了？

### ISSUE THREAD

**Issue by wenhx** [cnblogs/cnblogs-hardening#246]
在管理后台的右上角，有一个备份的链接，指向这个地址：https://i1.cnblogs.com/BlogBackup.aspx ，但是无法正常访问。
想备份一下博客，以防万一。

**Comment by cnblogs-team** [comment]
您好，现在已经回复正常，非常非常抱歉，由于github邮件通知问题，现在才回复您，请谅解

**Comment by wenhx** [comment]
能用了。
我还写了一个[小工具](https://github.com/wenhx/CnblogsBackupViewer)用来浏览备份。
