### ISSUE TITLE
请尽快审核，谢谢

### ISSUE THREAD

**Issue by SuperMuscleMan** [cnblogs/cnblogs-hardening#269]
博文内容均是Erlang语言相关的珍惜知识
地址如下：
https://www.cnblogs.com/zhengsyao/p/erlang_eterm_implementation_1.html
https://www.cnblogs.com/zhengsyao/p/erlang_eterm_implementation_2.html
https://www.cnblogs.com/zhengsyao/p/erlang_eterm_implementation_3.html
https://www.cnblogs.com/zhengsyao/p/erlang_eterm_implementation_4.html

**Comment by cnblogs-team** [comment]
您好，已审核通过，非常非常抱歉，由于github邮件通知问题，现在才处理，请谅解
