### ISSUE TITLE
请尽快审核

### ISSUE THREAD

**Issue by JohnWSY** [cnblogs/cnblogs-hardening#270]
内容关于kenlm训练语言模型
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2FClimbing-Snail%2Fp%2F9519079.html

**Comment by cnblogs-team** [comment]
您好，已审核通过，非常非常抱歉，由于github邮件通知问题，现在才处理，请谅解
https://www.cnblogs.com/Climbing-Snail/p/9519079.html
