### ISSUE TITLE
麻烦审核下这篇RC低通滤波器的c语言实现

### ISSUE THREAD

**Issue by zq1lalala** [cnblogs/cnblogs-hardening#303]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Funclemac%2Fp%2F12783347.html

**Comment by cnblogs-team** [comment]
您好，已审核通过，非常非常抱歉，由于github邮件通知问题，现在才回复您，请谅解

https://www.cnblogs.com/unclemac/p/12783347.html
