### ISSUE TITLE
麻煩幫忙審核這篇Kaldi log-probability相關的文章，感謝~

### ISSUE THREAD

**Issue by shuuennokage** [cnblogs/cnblogs-hardening#333]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2FJarvanWang%2Fp%2F10145889.html

**Comment by cnblogs-team** [comment]
您好，已审核通过，非常非常抱歉，由于github邮件通知问题，现在才处理，请谅解
https://www.cnblogs.com/JarvanWang/p/10145889.html
