### ISSUE TITLE
麻烦进行审核

### ISSUE THREAD

**Issue by SuzukazeHaruka** [cnblogs/cnblogs-hardening#352]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Ffumj%2Farchive%2F2012%2F09%2F12%2F2682039.html

**Comment by cnblogs-team** [comment]
您好，已审核通过，非常抱歉，由于github邮件通知问题，现在才回复您
