### ISSUE TITLE
麻烦加快审核

### ISSUE THREAD

**Issue by zhhqiang3** [cnblogs/cnblogs-hardening#359]
![image](https://user-images.githubusercontent.com/20870394/113273792-95166f00-930f-11eb-9012-3b382b649b34.png)
Swagger PHP使用指南- derrck - 博客园

**Comment by cnblogs-team** [comment]
您好，已审核通过，非常抱歉，由于github邮件通知问题，现在才回复您
https://www.cnblogs.com/derrck/p/5234961.html
