### ISSUE TITLE
请尽快审核

### ISSUE THREAD

**Issue by paichien** [cnblogs/cnblogs-hardening#385]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2FgoWithHappy%2Fp%2Fbuild-skywalking-in-windows.html

**Comment by cnblogs-team** [comment]
您好，已审核通过，非常抱歉，由于github邮件通知问题，现在才回复您
https://www.cnblogs.com/goWithHappy/p/build-skywalking-in-windows.html
