### ISSUE TITLE
1

### ISSUE THREAD

**Issue by angangxuxu** [cnblogs/cnblogs-hardening#403]

**Comment by mrp8ge8** [comment]
又不给钱 又挑剔

**Comment by xuchuanchaoxu** [comment]
> 又不给钱 又挑剔

要么你就是直接关掉网站，你既然提供服务，每个人都有挑剔的资格

**Comment by mrp8ge8** [comment]
> > 又不给钱 又挑剔
> 
> 要么你就是直接关掉网站，你既然提供服务，每个人都有挑剔的资格

感谢党，感谢人民

**Comment by cnblogs-team** [comment]
您好，非常抱歉，由于github邮件通知问题，没能及时处理issue

**Comment by angangxuxu** [comment]
> > > 又不给钱 又挑剔
> > 
> > 
> > 要么你就是直接关掉网站，你既然提供服务，每个人都有挑剔的资格
> 
> 感谢党，感谢人民

感谢你全家
