### ISSUE TITLE
麻烦尽快审核这两篇技术文章，想着清明放假有时间跟着操作下

### ISSUE THREAD

**Issue by 1987skywalker** [cnblogs/cnblogs-hardening#411]
https://www.cnblogs.com/u128393/p/11629971.html
https://www.cnblogs.com/u128393/p/11629970.html
技术文章，全网唯一的方案，比较复杂，留言也有技术讨论，之前想着清明放假有时间操作下，结果一看被屏蔽了……

**Comment by cnblogs-team** [comment]
您好，已审核通过，非常抱歉，由于github邮件通知问题，现在回复您
