### ISSUE TITLE
请尽快审核 谢谢

### ISSUE THREAD

**Issue by zqc-hhg** [cnblogs/cnblogs-hardening#42]
https://www.cnblogs.com/cmt/p/14553189.html#tcache-attack

**Comment by cnblogs-team** [comment]
您好，博文地址不对，麻烦提供一下博文标题

**Comment by zqc-hhg** [comment]
玩转堆 堆漏洞利用的技巧

**Comment by cnblogs-team** [comment]
您好，已审核通过，抱歉，给您带来麻烦了
https://www.cnblogs.com/pwn-the-world/audit/posts/7627275
