### ISSUE TITLE
麻烦审核此单片机博文，谢谢

### ISSUE THREAD

**Issue by retsyo** [cnblogs/cnblogs-hardening#425]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fmyfish3%2Fp%2F13345004.html

**Comment by cnblogs-team** [comment]
您好，已审核通过，非常抱歉，由于github邮件通知问题，现在才帮您处理
https://www.cnblogs.com/myfish3/p/13345004.html
