### ISSUE TITLE
请求审核，感谢

### ISSUE THREAD

**Issue by Bepo12138** [cnblogs/cnblogs-hardening#481]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fhust2012%2Farchive%2F2012%2F11%2F08%2F2760862.html

**Comment by cnblogs-team** [comment]
您好，抱歉，给您带来麻烦了，已审核通过 https://www.cnblogs.com/hust2012/archive/2012/11/08/2760862.html
