### ISSUE TITLE
请求审核

### ISSUE THREAD

**Issue by mark12138** [cnblogs/cnblogs-hardening#484]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fmchina%2Farchive%2F2013%2F01%2F01%2F2840815.html

**Comment by cnblogs-team** [comment]
您好，抱歉，给您带来麻烦了，已审核通过 https://www.cnblogs.com/mchina/archive/2013/01/01/2840815.html
