### ISSUE TITLE
请求快速通过两个网址

### ISSUE THREAD

**Issue by wuji111** [cnblogs/cnblogs-hardening#496]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fshowker%2Fp%2F4324546.html

https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fhannyblogs%2Fp%2F6535664.html

**Comment by cnblogs-team** [comment]
您好，抱歉，给您带来麻烦了，已审核通过
https://www.cnblogs.com/showker/p/4324546.html
https://www.cnblogs.com/hannyblogs/p/6535664.html
