### ISSUE TITLE
真的好慢，快些审核完了，有急事

### ISSUE THREAD

**Issue by Enterpriseman** [cnblogs/cnblogs-hardening#553]

**Comment by cnblogs-team** [comment]
您好，麻烦您提供一下博文地址

**Comment by Enterpriseman** [comment]
https://www.baidu.com/link?url=dc0ThgO-YIrQ8ha-BebA2m-mWlgnP_JLM7CAve_TbRFAN6S2o-QF9_CwnDX7kBG6r8XEzy8epHLNHfB6n0v1s_&amp;wd=&amp;eqid=a64ca117000a8edb00000006606c7645




https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fitjunjun%2Fp%2F13078746.html




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月6日(星期二) 晚上10:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cnblogs/cnblogs-hardening] 真的好慢，快些审核完了，有急事 (#553)





 
您好，麻烦您提供一下博文地址

**Comment by cnblogs-team** [comment]
您好，抱歉，给您带来麻烦了，已审核通过
https://www.cnblogs.com/itjunjun/p/13078746.html
