### ISSUE TITLE
帮忙审核一下 谢谢

### ISSUE THREAD

**Issue by kobeisgod** [cnblogs/cnblogs-hardening#555]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fjcli%2Fp%2Fcalendar_recur_rule.html 
这篇文章最近需要看一下 《日历设计之重复事件规则设计》

**Comment by cnblogs-team** [comment]
您好，抱歉，给您带来麻烦了，已审核通过
https://www.cnblogs.com/jcli/p/calendar_recur_rule.html
