### ISSUE TITLE
请审核一下

### ISSUE THREAD

**Issue by Blinkblade** [cnblogs/cnblogs-hardening#629]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fkid-li%2Farchive%2F2007%2F09%2F04%2F881725.html
这篇，最近一个作业要查阅本篇资料，感谢！

**Comment by cnblogs-team** [comment]
您好，抱歉，给您带来麻烦了，已审核通过
https://www.cnblogs.com/kid-li/archive/2007/09/04/881725.html
