### ISSUE TITLE
请审核一下

### ISSUE THREAD

**Issue by ZhRANDOM** [cnblogs/cnblogs-hardening#640]
https://www.cnblogs.com/cmt/p/14580194.html

**Comment by cnblogs-team** [comment]
您好，博文地址不对，麻烦您提供一下正确的博文地址或者标题

**Comment by ZhRANDOM** [comment]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Ffreven%2Fp%2F12995929.html

标题是：spring boot+jpa+mysql实现简单的登录注册–尚由-博客园

**Comment by cnblogs-team** [comment]
您好，已审核通过，抱歉，给您带来麻烦了
https://www.cnblogs.com/freven/p/12995929.html
