### ISSUE TITLE
麻烦审核下，谢谢

### ISSUE THREAD

**Issue by SummerDiver** [cnblogs/cnblogs-hardening#658]
https://www.cnblogs.com/cmt/p/14580194.html

并行计算——基于MPI实现埃拉托斯特尼筛法及性能优化

辛苦啦

**Comment by SummerDiver** [comment]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fpanern%2Fp%2F12971281.html

**Comment by cnblogs-team** [comment]
您好，已审核通过，抱歉，给您带来麻烦了
https://www.cnblogs.com/panern/p/12971281.html
