### ISSUE TITLE
都快三个星期了，还没有更新完？敏感词筛选还有分散审核任务不行吗？

### ISSUE THREAD

**Issue by cgr20171202** [cnblogs/cnblogs-hardening#662]
我的360浏览器一搜索开头几个必定是cnblogs，一直也没有屏蔽。我也是醉了。打开就是非常抱歉……我都要看吐了。
前几年我想申请开通博客，之前好像可以发博客的，结果后来需要资格审核，然后后来还是没有开通。我就懒得开通了，就在csdn算了。
我以前投诉建议在博客开头加上发布时间，因为it更新太快了，在搜索引擎不是总能够看清楚时间再点进去，然后到最后一栏才看到时间可能太晚。其他博客网站包括csdn和简书都是这样。博客园愣是不改。
csdn也没有什么开博客审核，只是提示不能发政治或者其他相关。结果都没事。
现在一个做IT技术分享的，在it审核任务上折腾了大半个月，还要继续，还要用人工……这到底想打脸it还是自己？

**Comment by wunaozai** [comment]
有些事你不清楚，这次可能是同行举报。
cnblogs博客园作为非盈利博客，除了站长，没有太多的人力投入。
审核慢要多谅解。我是觉得处理态度挺好的。

**Comment by cgr20171202** [comment]
> 有些事你不清楚，这次可能是同行举报。
> cnblogs博客园作为非盈利博客，除了站长，没有太多的人力投入。
> 审核慢要多谅解。我是觉得处理态度挺好的。

好吧，感谢博客园，站长们辛苦了！希望以后一切顺利！
