### ISSUE TITLE
麻烦审核一下 求求了

### ISSUE THREAD

**Issue by madewtfaka** [cnblogs/cnblogs-hardening#682]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fgeorgewing%2Farchive%2F2009%2F09%2F29%2F1576641.html

**Comment by syluser** [comment]
https://www.cnblogs.com/nzg-noway/articles/6524952.html

**Comment by cnblogs-team** [comment]
您好，已审核通过，抱歉，给您带来麻烦了
https://www.cnblogs.com/georgewing/archive/2009/09/29/1576641.html
https://www.cnblogs.com/nzg-noway/articles/6524952.html
