### ISSUE TITLE
请审核一下

### ISSUE THREAD

**Issue by SuzukazeHaruka** [cnblogs/cnblogs-hardening#688]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fsky100%2Farchive%2F2009%2F05%2F14%2F1456723.html

**Comment by cnblogs-team** [comment]
您好，已审核通过，抱歉，给您带来麻烦了
https://www.cnblogs.com/sky100/archive/2009/05/14/1456723.html
