### ISSUE TITLE
麻烦审核一下辛苦了

### ISSUE THREAD

**Issue by WangSanjiang** [cnblogs/cnblogs-hardening#691]
这个是地址：https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fit_han_ku%2Farchive%2F2009%2F10%2F21%2F1587317.html
谢谢！！

**Comment by cnblogs-team** [comment]
您好，已审核通过，抱歉，给您带来麻烦了
https://www.cnblogs.com/it_han_ku/archive/2009/10/21/1587317.html
