### ISSUE TITLE
麻烦审核一下，辛苦啦！多谢！

### ISSUE THREAD

**Issue by bluewaterstar** [cnblogs/cnblogs-hardening#716]
https://www.cnblogs.com/cmt/p/14580194.html

**Comment by cnblogs-team** [comment]
您好，博文地址不对，麻烦您提供一下正确的博文地址或者标题

**Comment by bluewaterstar** [comment]
抱歉！给您添麻烦了，标题是：Ambari 节点服务器系统崩溃，重装agent和组件

https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Flianglianggege%2Fp%2F9402133.html

**Comment by cnblogs-team** [comment]
您好，已审核通过，抱歉，给您带来麻烦了
https://www.cnblogs.com/lianglianggege/p/9402133.html
