### ISSUE TITLE
麻烦审核下，感谢

### ISSUE THREAD

**Issue by DaiShuss** [cnblogs/cnblogs-hardening#717]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fsoniclq%2Farchive%2F2011%2F12%2F30%2F2307780.html

**Comment by cnblogs-team** [comment]
您好，已审核通过，抱歉，给您带来麻烦了
https://www.cnblogs.com/soniclq/archive/2011/12/30/2307780.html
