### ISSUE TITLE
麻烦审核一下，非常感谢

### ISSUE THREAD

**Issue by east-ebony** [cnblogs/cnblogs-hardening#731]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fgreenpepper%2Fp%2F14396961.html

**Comment by east-ebony** [comment]
博客标题：wsl2 参考的对象类型不支持尝试的操作 - 水拌青椒 - 博客园

**Comment by cnblogs-team** [comment]
您好，已审核通过，抱歉，给您带来麻烦了
https://www.cnblogs.com/greenpepper/p/14396961.html
