### ISSUE TITLE
请审核，感谢

### ISSUE THREAD

**Issue by PHizing** [cnblogs/cnblogs-hardening#745]
https://www.cnblogs.com/BlueDrop/p/3404523.html
标题：Android短信导入至IPhone
需要文章中该用户提供的http://files.cnblogs.com/BlueDrop/AndroidSmsToIPhone.zip文件下载

**Comment by cnblogs-team** [comment]
您好，已审核通过，抱歉，给您带来麻烦了

**Comment by PHizing** [comment]
神速啊，点赞
