### ISSUE TITLE
请审核一下该文章，谢谢！

### ISSUE THREAD

**Issue by DCTANT** [cnblogs/cnblogs-hardening#746]
https://www.cnblogs.com/cmt/p/14580194.html

**Comment by cnblogs-team** [comment]
您好，博文地址不对，麻烦您提供一下正确的博文地址或者标题

**Comment by DCTANT** [comment]
> 您好，博文地址不对，麻烦您提供一下正确的博文地址或者标题

https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Ffengyun2050%2Fp%2F12809204.html

这篇文章是关于PF4j，Java插件化功能的，从CSDN链接过来，如果不对的话，估计是被作者删了吧

**Comment by cnblogs-team** [comment]
您好，已审核通过，抱歉，给您带来麻烦了
https://www.cnblogs.com/fengyun2050/p/12809204.html
