### ISSUE TITLE
博客文章审核

### ISSUE THREAD

**Issue by VictorEdmund** [cnblogs/cnblogs-hardening#788]
Hi，
    https://www.cnblogs.com/liwangwang/p/11876433.html

以上地址请帮忙有限审核，感谢！

**Comment by cnblogs-team** [comment]
您好，激活破解方面的博文属于侵权内容，不能访问。

**Comment by GHMOBILEMARCH** [comment]
那岂不是以后只能用正版了？，，，
大哥给个活路啊！！！！！！！！！！
