### ISSUE TITLE
帮忙审核，谢谢

### ISSUE THREAD

**Issue by whg517** [cnblogs/cnblogs-hardening#792]
地址：https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fcodingleaf%2Fp%2F11780083.html

说明：我不是博客作者，此文章是我在百度搜索“六大设计原则”时的第一篇，百度搜索列表页有设计原则内容。希望能审核一下。感谢。

**Comment by cnblogs-team** [comment]
您好，已经审核了这个博客

**Comment by whg517** [comment]
谢谢
