### ISSUE TITLE
麻烦尽快审核，多谢！

### ISSUE THREAD

**Issue by xidianJZL** [cnblogs/cnblogs-hardening#80]
麻烦审核一下，这两个是博主自己总结的东西，一直在看没啥问题，他俩都是有一个系列的JVM的麻烦一起审核了吧，多谢
https://www.cnblogs.com/huangwenjie/p/13405145.html
https://www.cnblogs.com/xjwhaha/category/1873854.html?page=1

**Comment by cnblogs-team** [comment]
您好，抱歉，给您带来麻烦了，已审核通过

**Comment by xidianJZL** [comment]
感谢！希望博客园越办越好
