### ISSUE TITLE
请帮我，谢谢你

### ISSUE THREAD

**Issue by 1433223anpeng** [cnblogs/cnblogs-hardening#813]
https://www.cnblogs.com/cmt/p/14580194.html
谢谢你

**Comment by cnblogs-team** [comment]
您好，请您回复您希望优先审核的博文链接，这边看到的是审核公告的链接。

**Comment by 1433223anpeng** [comment]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fqisong%2Fp%2F14471243.html
有点不太懂这个url
百度搜索“rust编程 温度转换”
第一个就是(抱歉我太笨了)
我也建议能在gitee开一个这样的仓库，github有点不容易上

**Comment by cnblogs-team** [comment]
您好，已经审核了这个博客，很抱歉给您带来麻烦了。

**Comment by 1433223anpeng** [comment]
谢谢你
