### ISSUE TITLE
麻烦审核一下，谢谢了。

### ISSUE THREAD

**Issue by wanghuizzz** [cnblogs/cnblogs-hardening#902]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fsosoben%2Fp%2Fsosoben-tesseract.html

**Comment by cnblogs-team** [comment]
您好，已审核通过，抱歉，给您带来麻烦了
https://www.cnblogs.com/sosoben/p/sosoben-tesseract.html
