### ISSUE TITLE
请审核

### ISSUE THREAD

**Issue by tangyuan59** [cnblogs/cnblogs-hardening#956]
https://www.cnblogs.com/cmt/p/14580194.html?from=https%3A%2F%2Fwww.cnblogs.com%2Fdelav%2Fp%2F7845539.html

**Comment by cnblogs-team** [comment]
您好，抱歉，这篇博文包含领导人名称，不能恢复访问

**Comment by tangyuan59** [comment]
我哭了熬~~~
